version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: salazar
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL: "false"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql