services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: salazarPostgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: salazar
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL: "true"
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
