services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  mongo_data: